docs(README): add hertz extensions list
cloudwego/hertz pull request #307
Opened 2022-10-18 14:57 UTC by L2ncE

#### What type of PR is this?

docs

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en: add hertz extensions to the list in readme

#### Which issue(s) this PR fixes:

Fixes #305

2022-10-18 15:30 UTC, BaiZe1998 commented
我在 ci 时遇到了相同的问题，原因是 sonic 库的证书阻塞了用户的开发。
通过修改 .licenserc.yaml，sonic.go，std.go 文件，我解决了这个问题，详细改动可以查看如下pr：
https://github.com/cloudwego/hertz/pull/306

2022-10-18 16:29 UTC, li-jin-gou commented
参考不等于完全照抄

2022-10-18 16:39 UTC, li-jin-gou requested changes

2022-10-18 16:39 UTC, li-jin-gou commented on README_cn.md
> +| [registry](https://github.com/hertz-contrib/registry)        | 到现在为止，支持的服务发现拓展有 nacos， consul， etcd， eureka， polaris， servicecomb， zookeeper。 |
registry 没有描述作用

2022-10-18 16:39 UTC, li-jin-gou commented on README_cn.md
> +| [pprof](https://github.com/hertz-contrib/pprof)              | 通过其 HTTP 服务器运行时分析数据并以 pprof 可视化工具所期望的格式提供服务。 |
proof 读起来怪怪的

建议: Hertz 集成 pprof 的扩展

2022-10-18 16:39 UTC, li-jin-gou commented on README_cn.md
> +| [obs-opentelemetry](https://github.com/hertz-contrib/obs-opentelemetry) | 集成了默认 opentelemetry 程序，达到开箱即用并支持设置环境变量。 |
介绍不全面

建议: Hertz 的 Opentelemetry 扩展，支持 Metric、Logger、Tracing并且达到开箱即用。

2022-10-18 16:39 UTC, li-jin-gou commented on README_cn.md
> +| [sentry](https://github.com/hertz-contrib/hertzsentry)       | sentry 拓展提供了一些统一的接口来帮助用户获取哨兵中心以及报告错误信息。 |
获取哨兵中心 是什么意思

2022-10-18 16:39 UTC, li-jin-gou commented on README_cn.md
> +| [limiter](https://github.com/hertz-contrib/limiter)          | 使用 bbr 算法，通过读取/proc/stat收集CPU负载，判断CPU负载触发限流条件。 |
提供了基于 bbr 算法的限流器

2022-10-18 16:39 UTC, li-jin-gou commented on README_cn.md
> +| [jwt](https://github.com/hertz-contrib/jwt)                  | JWT 返回一个 JSON Web Token(JWT) 身份验证中间件。            |
这个读起来怪怪的，你觉得呢

2022-10-18 16:39 UTC, li-jin-gou commented on README_cn.md
> +| [keyauth](https://github.com/hertz-contrib/keyauth)          | 提供基于密钥的身份验证。                                     |
密钥 => token

2022-10-18 16:39 UTC, li-jin-gou commented on README_cn.md
> +| [monitor-prometheus](https://github.com/hertz-contrib/monitor-prometheus) | Prometheus 中存储的数据为时间序列，是由 metric 的名字和一系列的标签（键值对）唯一标识的，不同的标签则代表不同的时间序列。 |
感觉这个是在介绍 prometheus 了

2022-10-18 16:39 UTC, li-jin-gou commented on README_cn.md
> +| [tracer](https://github.com/hertz-contrib/tracer)            | 能够快速在 Hertz 中启用链路追踪功能。                        |
基于 opentracing 的链路追踪

2022-10-18 16:44 UTC, li-jin-gou commented on README_cn.md
> +| [requestid](https://github.com/hertz-contrib/requestid)      | 使用 X-Request-ID 标头向响应添加标识符，如果在请求标头中发送 X-Request-ID 值，则将其传递回调用方。 |
向响应中添加 requestid

2022-10-18 16:45 UTC, li-jin-gou commented on README_cn.md
> +| [websocket](https://github.com/hertz-contrib/websocket)      | 使 Hertz 支持 WebSocket 协议。                               |
我注意到有的单词首字母大写了，有的没有，这里需要统一一下

2022-10-19 00:12 UTC, L2ncE commented
> 我在 ci 时遇到了相同的问题。 通过修改 .licenserc.yaml，sonic.go，std.go 文件，我解决了这个问题，详细改动可以查看如下pr： #306

i got it, thx.

2022-10-19 01:10 UTC, L2ncE commented on README_cn.md
> +| [registry](https://github.com/hertz-contrib/registry)        | 到现在为止，支持的服务发现拓展有 nacos， consul， etcd， eureka， polaris， servicecomb， zookeeper。 |
> registry 没有描述作用

done

2022-10-19 01:10 UTC, L2ncE commented on README_cn.md
> +| [obs-opentelemetry](https://github.com/hertz-contrib/obs-opentelemetry) | 集成了默认 opentelemetry 程序，达到开箱即用并支持设置环境变量。 |
> 介绍不全面
> 
> 建议: Hertz 的 Opentelemetry 扩展，支持 Metric、Logger、Tracing并且达到开箱即用。

done

2022-10-19 01:10 UTC, L2ncE commented on README_cn.md
> +| [sentry](https://github.com/hertz-contrib/hertzsentry)       | sentry 拓展提供了一些统一的接口来帮助用户获取哨兵中心以及报告错误信息。 |
> 获取哨兵中心 是什么意思

已修改

2022-10-19 01:11 UTC, L2ncE commented on README_cn.md
> +| [jwt](https://github.com/hertz-contrib/jwt)                  | JWT 返回一个 JSON Web Token(JWT) 身份验证中间件。            |
> 这个读起来怪怪的，你觉得呢

之前参考的 fiber，已修改

2022-10-19 01:11 UTC, L2ncE commented on README_cn.md
> +| [monitor-prometheus](https://github.com/hertz-contrib/monitor-prometheus) | Prometheus 中存储的数据为时间序列，是由 metric 的名字和一系列的标签（键值对）唯一标识的，不同的标签则代表不同的时间序列。 |
> 感觉这个是在介绍 prometheus 了

已修改

2022-10-19 01:11 UTC, L2ncE commented on README_cn.md
> +| [opensergo](https://github.com/hertz-contrib/opensergo)      | 提供 opensergo 的哨兵适配器。                                |
> 哨兵 => Sentinel
> 
> 这里还有一个问题是 上文和当前都翻译为 哨兵 会让人迷惑 @L2ncE
> 
> 建议: opensergo 扩展

done

2022-10-19 01:12 UTC, L2ncE commented on README_cn.md
> +| [sessions](https://github.com/hertz-contrib/sessions)        | 具有多后端支持的 session 中间件。                            |
> 多状态后端 => 多状态存储

done

2022-10-19 01:12 UTC, L2ncE commented on README_cn.md
> +| [websocket](https://github.com/hertz-contrib/websocket)      | 使 Hertz 支持 WebSocket 协议。                               |
> 我注意到有的单词首字母大写了，有的没有，这里需要统一一下

done

2022-10-19 03:04 UTC, li-jin-gou commented on README_cn.md
> +| [requestid](https://github.com/hertz-contrib/requestid)                   | 使用 X-Request-ID 标头向响应中添加 requestid，如果在请求标头中发送 X-Request-ID 值，则将其传递回调用方。                    |
在 response 中添加 request id

2022-10-19 03:16 UTC, L2ncE commented on README_cn.md
> +| [requestid](https://github.com/hertz-contrib/requestid)                   | 使用 X-Request-ID 标头向响应中添加 requestid，如果在请求标头中发送 X-Request-ID 值，则将其传递回调用方。                    |
> 在 response 中添加 request id

done

2022-10-19 03:16 UTC, L2ncE commented on README_cn.md
> +| [jwt](https://github.com/hertz-contrib/jwt)                               | 身份验证中间件，提供生成 token 以及刷新 token 的功能。                                                         |
> JWT 扩展

done

2022-10-19 07:19 UTC, welkeyever approved these changes
lgtm, thx~

2022-10-19 12:17 UTC, li-jin-gou requested changes

2022-10-19 12:17 UTC, li-jin-gou commented on README_cn.md
> +| [Websocket](https://github.com/hertz-contrib/websocket)                   | 使 Hertz 支持 Websocket 协议。                                                                   |
把 Recovery 和 BasicAuth 也加上吧
https://github.com/cloudwego/hertz/tree/develop/pkg/app/middlewares/server

2022-10-19 12:27 UTC, L2ncE commented on README_cn.md
> +| [Websocket](https://github.com/hertz-contrib/websocket)                   | 使 Hertz 支持 Websocket 协议。                                                                   |
> 

done

2022-10-20 06:28 UTC, welkeyever approved these changes

2022-10-20 06:28 UTC, merged