optimize: A new optimization for simplifying writing UT file.
cloudwego/hertz pull request #333
Opened 2022-10-28 08:13 UTC by learningpro

#### What type of PR is this?

#### Check the PR title.

- [x] This PR title match the format: \<type\>(optional scope): \<description\>
- [x] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.
简化单测文件编写流程，避免在单测文件中重写handler里出现过的业务逻辑

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en:
![image](https://user-images.githubusercontent.com/1081377/198536770-06d30967-d25d-4601-ab42-ab848e258864.png)
As shown in the picture from Hertz example, those logic code should already be in the handler file. For the *_test.go UT file, it's not a good practice to copy and pace those code again. Every time we change the handler file, we need to copy again into test file.
Using this PR fix, we can write UT in the way below:
![image](https://user-images.githubusercontent.com/1081377/198537497-209a8edd-5d5d-4fd0-abd6-6fd217c850d2.png)
There is no need to copy logic code again now.

zh(optional):
![image](https://user-images.githubusercontent.com/1081377/198536770-06d30967-d25d-4601-ab42-ab848e258864.png)
从Hertz的示例代码中可以看到，为了写单元测试代码，需要将接口逻辑在单测函数中重写一遍，但是如果接口逻辑改过了，单测文件中也需要重新复制粘贴一遍，较为麻烦。
通过本PR改动，可以用下面的示例方法来写单测：
![image](https://user-images.githubusercontent.com/1081377/198537497-209a8edd-5d5d-4fd0-abd6-6fd217c850d2.png)
不再需要复制粘贴业务逻辑代码。
#### Which issue(s) this PR fixes:

2022-10-28 08:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudwego/hertz?pullRequest=333) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudwego/hertz?pullRequest=333) before we can accept your contribution.<br/><hr/>**dongjiancheng** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudwego/hertz?pullRequest=333) it.</sub>

2022-10-28 08:37 UTC, li-jin-gou requested changes

2022-10-28 08:37 UTC, li-jin-gou commented on pkg/common/ut/request.go
> +func PerformBizServerRequest(bizServer *server.Hertz, method, url string, body *Body, headers ...Header) *ResponseRecorder {
I think this is a good note and needs to be supplemented with unit tests as well as comments

2022-10-28 09:01 UTC, learningpro commented on pkg/common/ut/request.go
> +func PerformBizServerRequest(bizServer *server.Hertz, method, url string, body *Body, headers ...Header) *ResponseRecorder {
Yes, I update it again with more comments.  Could you please give me a suggestion where handler file should I add to make unit tests for it? Is it OK to add ping.go and ping_test.go in pkg/common/ut folder ？

2022-10-28 09:25 UTC, Duslia commented on pkg/common/ut/request.go
> +func PerformBizServerRequest(bizServer *server.Hertz, method, url string, body *Body, headers ...Header) *ResponseRecorder {
emmm 我感觉这个用户自己搞下应该就行？ Hertz 提供一个 PerformRequest 方法就好。

2022-10-28 09:45 UTC, learningpro commented on pkg/common/ut/request.go
> +func PerformBizServerRequest(bizServer *server.Hertz, method, url string, body *Body, headers ...Header) *ResponseRecorder {
It will be more user-friendly for new user. I faced this issue, maybe there are some others facing the same problem.

2022-10-31 03:55 UTC, welkeyever commented on pkg/common/ut/request_test.go
> +	w := PerformBizServerRequest(h, "GET", "/ping", &Body{bytes.NewBufferString("1"), 1},
`w := PerformRequest(h.Engine, "GET", "/ping", &Body{bytes.NewBufferString("1"), 1},` is equal to line 124?

2022-10-31 11:33 UTC, welkeyever commented
covered by `w := PerformRequest(h.Engine, "GET", "/ping", &Body{bytes.NewBufferString("1"), 1}`

2022-10-31 11:33 UTC, closed without merging