feat: support client and server writetimeout
cloudwego/hertz pull request #344
Opened 2022-11-03 05:36 UTC by Duslia

#### What type of PR is this?
feat
#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en: support client and server writetimeout
zh(optional): 支持 client 和 server 的 writetimeout

#### Which issue(s) this PR fixes:

2022-11-04 03:34 UTC, Duslia commented
In the case of setting MaxConnWaitTimeout, if the number of connections in the connection pool exceeds the maximum number of connections and needs to establish a connection while waiting, the dialtimeout on the hostclient is used  instead of the dialtimeout in request options.

在设置了MaxConnWaitTimeout的情况下，如果连接池连接数超过了最大连接数量等待时需要建立连接的情况下，使用的是hostclient 上的dialtimeout 而不是 req options 里的 dialtimeout

2022-11-10 09:06 UTC, welkeyever commented on pkg/protocol/http1/client.go
> +		// the dialtimeout in request options.
also add explanation on the commentary of client.ClientOptions.DialTimeout field

2022-11-10 09:06 UTC, welkeyever commented on pkg/protocol/request.go
> +	req.Options().Reset()
will break the init way of req.options since it will skip the `preDefinedOpts` logic at the next round.

2022-11-11 09:22 UTC, li-jin-gou requested changes

2022-11-11 09:22 UTC, li-jin-gou commented on pkg/common/config/request_option.go
> +	DialTimeout  time.Duration
Style needs to be consistent.

such as 
```
func (o *RequestOptions) Tag(k string) string {
	return o.tags[k]
}
func (o *RequestOptions) Tags() map[string]string {
	return o.tags
}
func (o *RequestOptions) IsSD() bool {
	return o.isSD
}
```

2022-11-11 09:22 UTC, li-jin-gou commented on pkg/protocol/http1/client.go
> +	rc := c.preHandleConfig(req.Options())
Why not just use the option here and use a custom structure instead?

2022-11-11 09:35 UTC, li-jin-gou commented on pkg/common/config/request_option.go
> +	DialTimeout  time.Duration
It looks strange, with uppercase and lowercase, with Getter and without Getter.

2022-11-11 09:41 UTC, li-jin-gou commented on pkg/protocol/http1/client.go
> +	rc := c.preHandleConfig(req.Options())
This is to determine the timeout with the conn and to set the default value.

2022-11-11 09:45 UTC, li-jin-gou submitted a review, later dismissed

2022-11-11 11:50 UTC, welkeyever approved these changes

2022-11-11 11:50 UTC, li-jin-gou approved these changes

2022-11-11 12:06 UTC, merged