Update context.go
cloudwego/hertz pull request #369
Opened 2022-11-14 10:24 UTC by morebuff

Add GetUint64(key string) to context.go

#### What type of PR is this?

#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en:
zh(optional):

#### Which issue(s) this PR fixes:

2022-11-14 10:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudwego/hertz?pullRequest=369) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudwego/hertz?pullRequest=369) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudwego/hertz?pullRequest=369) it.</sub>

2022-11-14 10:26 UTC, L2ncE commented
Hi, thanks for ur pr. I think u need to fill in the pr title and description according to the pr template.❤️

2022-11-14 10:27 UTC, li-jin-gou requested changes

2022-11-14 10:27 UTC, li-jin-gou commented on pkg/app/context.go
> +func (ctx *RequestContext) GetUint64(key string) (ui64 uint64) {
I think the Get*** methods need to be added and should be well commented with a single test.

2022-11-15 11:48 UTC, li-jin-gou commented
refer to https://github.com/cloudwego/hertz/pull/375

2022-11-15 11:48 UTC, closed without merging