fix: standard context use the same one in http1.Serve
cloudwego/hertz pull request #373
Opened 2022-11-14 13:10 UTC by Duslia

#### What type of PR is this?

fix
#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.
en: standard context use the same one in http1.Serve. In the case of long connections, it will cause the context to become larger and larger, resulting in greater overhead.
zh: http1 Serve 方法中使用同一个 context。在长连接情况下，会导致 context 越来越大，导致开销更大。

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en:
zh(optional):

#### Which issue(s) this PR fixes:

2022-11-14 13:12 UTC, welkeyever approved these changes

2022-11-14 13:28 UTC, L2ncE approved these changes

2022-11-14 13:46 UTC, welkeyever requested changes
better use the origin ctx to reset？

2022-11-15 02:56 UTC, FGYFFFF commented on pkg/protocol/http1/server.go
> +		cx := c
cx可以画个变量名嘛， 这个代码里 c，cx，ctx，不了解背景的话很快就迷糊了 = =

2022-11-15 11:38 UTC, Duslia commented on pkg/protocol/http1/server.go
> +		cx := c
I think it's OK. What name you think is more suitable?

2022-11-16 06:56 UTC, welkeyever approved these changes

2022-11-16 06:56 UTC, li-jin-gou approved these changes

2022-11-16 06:59 UTC, FGYFFFF approved these changes

2022-11-16 07:08 UTC, merged