fix: connection pool leak
cloudwego/hertz pull request #625
Opened 2023-02-20 12:34 UTC by wzekin

#### What type of PR is this?

fix
#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.
修复链接池泄漏

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en: When the client uses bodystream to receive data, if the user uses netpoll and does not close the bodyStream properly, it can cause a link pool leak. Use `runtime.SetFinalizer` as a bailout to close the bodyStream.
zh(optional): 在 client 使用 bodystream 接收数据的时候，如果用户使用 netpoll 且没有正确关闭 bodyStream，则会造成链接池泄漏。使用 `runtime.SetFinalizer` 作为保底措施来关闭bodyStream。

#### Which issue(s) this PR fixes:

2023-02-21 08:25 UTC, welkeyever approved these changes, later dismissed

2023-02-22 06:18 UTC, Duslia approved these changes

2023-02-22 06:24 UTC, Duslia requested changes

2023-02-22 06:24 UTC, Duslia commented on pkg/protocol/http1/client_test.go
>  	"time"
some usesless comments to dismiss approve

2023-02-22 07:42 UTC, FGYFFFF approved these changes, later dismissed

2023-02-24 06:14 UTC, Duslia approved these changes

2023-02-24 06:28 UTC, FGYFFFF approved these changes

2023-02-24 06:28 UTC, merged