Add:Support multiple request query parameters
cloudwego/hertz pull request #659
Opened 2023-03-10 02:52 UTC by Feizekai

#### What type of PR is this?

#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en:
zh(optional):

#### Which issue(s) this PR fixes:

2023-03-10 02:58 UTC, FGYFFFF commented
Please write the description of this feature~

2023-03-10 03:17 UTC, Feizekai commented
> 


> Please write the description of this feature~

done it

2023-03-15 10:30 UTC, welkeyever commented on pkg/protocol/request.go
> +	builder.Write([]byte("?"))
No need to add "?", check here: https://github.com/cloudwego/hertz/blob/develop/pkg/protocol/uri.go#L653

2023-03-15 10:32 UTC, welkeyever commented on pkg/protocol/request.go
> +	builder.Write([]byte("?"))
Maybe add the correctness check in UTs.

2023-03-18 10:32 UTC, a631807682 commented on pkg/protocol/request.go
> +		builder.Write([]byte(k))
What happens if there are special characters? Do I need to use `url.QueryEscape`?
```go
	{
		"name": "cx&k=1",
		"age":  "25",
	}
```

2023-03-20 03:09 UTC, li-jin-gou commented
The query parameter may be an array

```
a=1&a=2&a=3
```

2023-03-22 06:30 UTC, welkeyever commented
@Feizekai Any update for this? 🙏

2023-03-23 02:48 UTC, li-jin-gou requested changes

2023-03-23 02:48 UTC, li-jin-gou commented on pkg/protocol/request.go
> +		queryString += fmt.Sprintf("%s=%s&", k, v)
use `strings.Builder` instead of it.

2023-03-23 02:50 UTC, li-jin-gou commented
I wonder do you have a real world example of this use?

2025-01-16 16:38 UTC, closed without merging