[WIP]feat(hz): generate docs when use `hz new`
cloudwego/hertz pull request #732
Opened 2023-04-18 06:23 UTC by Skyenought

#### What type of PR is this?

#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.

#### (Optional) Translate the PR title into Chinese.

#### (Optional) More detail description for this PR(en: English/zh: Chinese).

en:
zh(optional):

#### Which issue(s) this PR fixes:

2023-04-18 16:35 UTC, li-jin-gou commented
@Skyenought  是否可以将 markdown 的介绍作为 layout 模版的一部分，放到 https://github.com/Skyenought/hertz/blob/develop/cmd/hz/generator/layout_tpl.go#L44 这里，并且用户使用 hz 创建项目默认会创建英文的介绍，这里不需要中文，这个比较倾向作为一个默认行为用来引流&&效果应该会很好 cc @FGYFFFF @welkeyever

2023-04-18 16:45 UTC, li-jin-gou requested changes

2023-04-18 16:45 UTC, li-jin-gou commented on cmd/hz/docs/guide.md
> +English | [中文](guide_cn.md)
替换 ❤️❤️ If you like Hertz, don't forget to give us a star on [Github](https://github.com/cloudwego/hertz) ❤️❤️

2023-04-18 16:45 UTC, li-jin-gou commented on cmd/hz/docs/guide.md
> +### Middlewares
Hertz 支持的扩展能力列表 这样描述会准确些。

2023-04-18 16:45 UTC, li-jin-gou commented on cmd/hz/docs/guide.md
> +## Basic Usage
添加官方文档的链接&&更新一个项目的介绍更加需要

2023-04-20 11:54 UTC, FGYFFFF commented
rebase代码。落后了 N 个版本啦~

2023-10-28 13:11 UTC, closed without merging