fix: fix error printing of escaped characters in accesslog
cloudwego/hertz pull request #819
Opened 2023-06-17 13:05 UTC by Skyenought

#### What type of PR is this?
fix

#### Check the PR title.

- [x] This PR title match the format: `<type>(optional scope): <description>`.
- [x] The description of this PR title is user-oriented and clear enough for others to understand.
- [x] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io).

#### (Optional) Translate the PR title into Chinese.
修复在 accesslog中打印转义字符报错

#### (Optional) More detail description for this PR(en: English/zh: Chinese).
zh: 在 https://github.com/cloudwego/hertz/issues/807 中会出现打印转义字符出错的问题

原因:
在 v 为 nil 时, format 充满了含有 % 的转义字符, 就会出现类似 %!C(MISSING) 的转义字符缺失的问题

解决方案:
增加 v 是否为 nil 的判断, 通过判断使用不同的打印日志的方法

en:
zh(optional):

#### (Optional) Which issue(s) this PR fixes:
https://github.com/cloudwego/hertz/issues/807

#### (Optional) The PR that updates user documentation:

2023-06-17 15:08 UTC, li-jin-gou requested changes

2023-06-17 15:08 UTC, li-jin-gou commented on pkg/common/hlog/default.go
> +	if format != nil && len(v) > 0 {
add unit test

2023-06-17 15:28 UTC, Skyenought commented
at now? @li-jin-gou

2023-06-17 16:19 UTC, li-jin-gou approved these changes, later dismissed
LGTM

2023-08-23 07:16 UTC, welkeyever commented on pkg/common/hlog/default.go
> +	} else if format != nil && len(v) == 0 {
两个条件有相同的`format != nil`部分，考虑统一在一个外层分支处理，可以提升可读性：
```
if format != nil{
    if len(v) > 0{
        //
    } else {
        //
    }
}
```

2023-09-12 07:25 UTC, welkeyever approved these changes
LGTM, thx~

2023-09-18 14:29 UTC, Skyenought commented
@li-jin-gou Approve ?

2023-09-18 14:58 UTC, li-jin-gou approved these changes

2023-09-18 14:59 UTC, merged